trigger:
 branches:
   include:
     - main

pr:
  branches:
    include:
     - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: sonarcloud-credential-cellixjs
  - group: github-credential-cellixjs
  - name: deploymentDefaultLocation
    value: 'eastus2'
  - name: ServiceConnectionName
    value: 'ShareThrift-MSDN'
  - name: vmImageName
    value: 'ubuntu-latest'
  - name: system.debug
    value: true
  - name: pnpm_config_cache
    value: $(Pipeline.Workspace)/.pnpm-store
  - name: SONAR_USER_HOME
    value: $(Pipeline.Workspace)/.sonar

stages:
  - template: ./build-pipeline/core/monorepo-build-stage.yml
    parameters:
      vmImageName: $(vmImageName)
      pnpm_config_cache: $(pnpm_config_cache)
      isPnpmCacheAvailable: 'false'
      disableSonarCloudTasks: 'false'
      SONAR_USER_HOME: $(SONAR_USER_HOME)
      SonarCloud: 'sonarcloud'
      SonarCloud_organization: 'simnova'
      SonarCloud_scannerMode: 'CLI'
      SonarCloud_configMode: 'manual'
      SonarCloud_cliProjectKey: 'simnova_cellix-data-access'
      SonarCloud_cliProjectName: 'cellix-data-access'

  - template: ./build-pipeline/core/monorepo-deployment-stage.yml
    parameters:
      stageName: 'DEV'
      environmentNameBicep: 'dev'
      environmentNameDevOps: 'cellix-dev'
      vmImageName: $(vmImageName)
      ServiceConnectionName: $(ServiceConnectionName)
      deploymentDefaultLocation: $(deploymentDefaultLocation)
      resourceGroupName: 'rg-sharethrift'
      functionAppNamePri: 'Cellix-func-app'
      appSettingsJsonFileRelativePathPri: '/build-pipeline/config/dev-pri.json'