trigger:
 paths:
   include:
     - packages
 branches:
   include:
     - main

pr:
  branches:
    include:
      - main
  paths:
    include:
      - packages

pool:
  vmImage: ubuntu-latest

stages:
  - template: ./packages/api/build-pipelines/azure-pipelines.yml
