packages:
  - "apps/*"
  - "packages/arch-unit-tests"
  - "packages/cellix/*"
  - "packages/ocom/*"

catalog:
  '@azure/functions': 4.8.0
  graphql: ^16.10.0
  mongodb: 6.18.0
  mongoose: 8.17.0
  rimraf: 6.0.1
  typescript: 5.9.3
  vite: 7.1.12
  vitest: 3.2.4

overrides:
  node-forge@<1.3.2: '>=1.3.2'