packages:
  - apps/*
  - packages/arch-unit-tests
  - packages/cellix/*
  - packages/ocom/*

catalog:
  '@amiceli/vitest-cucumber': ^6.1.0
  '@azure/functions': 4.8.0
  '@vitest/coverage-v8': ^4.0.15
  graphql: ^16.10.0
  mongodb: 6.18.0
  mongoose: 8.17.0
  rimraf: 6.0.1
  typescript: 5.9.3
  vite: 7.1.12
  vitest: ^4.0.15

overrides:
  node-forge@<1.3.2: '>=1.3.2'
