import { describe, expect, it } from 'vitest';
import sidebars from './sidebars.ts';

describe('Sidebars Config', () => {
  it('should have valid sidebar configuration', () => {
    // Test that sidebars is defined and has the expected structure
    expect(sidebars).toBeDefined();
    expect(typeof sidebars).toBe('object');
  });

  it('should have docsSidebar configuration', () => {
    // Test that docsSidebar exists and is configured
    // biome-ignore lint:useLiteralKeys
    expect(sidebars['docsSidebar']).toBeDefined();
    // biome-ignore lint:useLiteralKeys 
    expect(Array.isArray(sidebars['docsSidebar'])).toBe(true);
  });

  it('should have autogenerated sidebar configuration', () => {
    // Test the autogenerated configuration
    const { docsSidebar } = sidebars;
    expect(Array.isArray(docsSidebar)).toBe(true);
    if (Array.isArray(docsSidebar)) {
      expect(docsSidebar).toHaveLength(1);
      expect(docsSidebar[0]).toEqual({
        type: 'autogenerated',
        dirName: '.',
      });
    }
  });

  it('should have proper sidebar structure for documentation', () => {
    expect(Object.keys(sidebars)).toContain('docsSidebar');
    
    // Test that the configuration is using the correct type
    const { docsSidebar } = sidebars;
    expect(Array.isArray(docsSidebar)).toBe(true);
    if (Array.isArray(docsSidebar)) {
      expect(docsSidebar[0]).toHaveProperty('type', 'autogenerated');
      expect(docsSidebar[0]).toHaveProperty('dirName', '.');
    }
  });
});
