import { createRequire } from 'node:module';
import { describe, expect, it } from 'vitest';

const require = createRequire(import.meta.url);
const sidebars = require('./sidebars.ts') as {
  docsSidebar: Array<{ type: string; dirName: string }>;
};

describe('Sidebars Config', () => {
  it('should have valid sidebar configuration', () => {
    expect(sidebars).toBeDefined();
    expect(typeof sidebars).toBe('object');
  });

  it('should have docsSidebar configuration', () => {
    // biome-ignore lint:useLiteralKeys
    expect(sidebars['docsSidebar']).toBeDefined();
    // biome-ignore lint:useLiteralKeys
    expect(Array.isArray(sidebars['docsSidebar'])).toBe(true);
  });

  it('should have autogenerated sidebar configuration', () => {
    const { docsSidebar } = sidebars;
    expect(Array.isArray(docsSidebar)).toBe(true);
    if (Array.isArray(docsSidebar)) {
      expect(docsSidebar).toHaveLength(1);
      expect(docsSidebar[0]).toEqual({
        type: 'autogenerated',
        dirName: '.',
      });
    }
  });

  it('should have proper sidebar structure for documentation', () => {
    expect(Object.keys(sidebars)).toContain('docsSidebar');

    const { docsSidebar } = sidebars;
    expect(Array.isArray(docsSidebar)).toBe(true);
    if (Array.isArray(docsSidebar)) {
      expect(docsSidebar[0]).toHaveProperty('type', 'autogenerated');
      expect(docsSidebar[0]).toHaveProperty('dirName', '.');
    }
  });
});
