// This file is auto-generated by build-pipeline/scripts/generate-graphql-bundler-manifests.mjs.
// Do not edit directly.

import resolver0 from '../types/community.resolvers.ts';
import resolver1 from '../types/end-user.resolvers.ts';
import resolver2 from '../types/member.resolvers.ts';
import resolver3 from '../types/test.resolvers.ts';

export const ocomGraphqlResolvers = [
	resolver0,
	resolver1,
	resolver2,
	resolver3,
];

export const ocomGraphqlPermissions = [
];
