import type { Config } from 'tailwindcss';

export default {
	content: [
		'./src/**/*.{js,jsx,ts,tsx}',
		'./index.html',
		'../../packages/ocom/ui-community-route-*/src/**/*.{js,jsx,ts,tsx}',
		'../../packages/ocom/ui-community-shared/src/**/*.{js,jsx,ts,tsx}',
	],
	theme: {
		extend: {
			colors: {
				'oc-almost-black': 'var(--oc-palette-almost-black)',
				'oc-dark-1': 'var(--oc-palette-dark-1)',
				'oc-dark-2': 'var(--oc-palette-dark-2)',
				'oc-mid-1': 'var(--oc-palette-mid-1)',
				'oc-mid-2': 'var(--oc-palette-mid-2)',
				'oc-light-1': 'var(--oc-palette-light-1)',
				'oc-light-2': 'var(--oc-palette-light-2)',
				'oc-almost-white': 'var(--oc-palette-almost-white)',
				'oc-white': 'var(--oc-palette-white)',
				'oc-success': 'var(--oc-palette-success)',
				'oc-warning': 'var(--oc-palette-warning)',
				'oc-error': 'var(--oc-palette-error)',
				'oc-info': 'var(--oc-palette-info)',
				'oc-primary': 'var(--oc-theme-primary)',
				'oc-background': 'var(--oc-theme-background)',
				'oc-surface': 'var(--oc-theme-surface)',
				'oc-surface-secondary': 'var(--oc-theme-surface-secondary)',
				'oc-text': 'var(--oc-theme-text)',
				'oc-text-secondary': 'var(--oc-theme-text-secondary)',
				'oc-border': 'var(--oc-theme-border)',
				'oc-border-strong': 'var(--oc-theme-border-strong)',
			},
			fontFamily: {
				outfit: ['Outfit', 'sans-serif'],
				'dm-sans': ['"DM Sans"', 'sans-serif'],
			},
			fontSize: {
				'oc-h1': ['var(--oc-font-size-h1)', { lineHeight: 'var(--oc-line-height-h1)', fontWeight: 'var(--oc-font-weight-bold)' }],
				'oc-h2': ['var(--oc-font-size-h2)', { lineHeight: 'var(--oc-line-height-h2)', fontWeight: 'var(--oc-font-weight-bold)' }],
				'oc-h3': ['var(--oc-font-size-h3)', { lineHeight: 'var(--oc-line-height-h3)', fontWeight: 'var(--oc-font-weight-bold)' }],
				'oc-body': ['var(--oc-font-size-body)', { lineHeight: 'var(--oc-line-height-body)', fontWeight: 'var(--oc-font-weight-regular)' }],
				'oc-body-bold': ['var(--oc-font-size-body)', { lineHeight: 'var(--oc-line-height-body)', fontWeight: 'var(--oc-font-weight-black)' }],
				'oc-caption': ['var(--oc-font-size-caption)', { lineHeight: 'var(--oc-line-height-caption)', fontWeight: 'var(--oc-font-weight-regular)' }],
			},
			spacing: {
				'oc-xxs': 'var(--oc-spacing-xxs)',
				'oc-xs': 'var(--oc-spacing-xs)',
				'oc-sm': 'var(--oc-spacing-sm)',
				'oc-md': 'var(--oc-spacing-md)',
				'oc-lg': 'var(--oc-spacing-lg)',
				'oc-xl': 'var(--oc-spacing-xl)',
				'oc-2xl': 'var(--oc-spacing-2xl)',
				'oc-3xl': 'var(--oc-spacing-3xl)',
				'oc-4xl': 'var(--oc-spacing-4xl)',
			},
			borderRadius: {
				'oc-sm': 'var(--oc-rounded-sm)',
				'oc-md': 'var(--oc-rounded-md)',
				'oc-lg': 'var(--oc-rounded-lg)',
				'oc-pill': 'var(--oc-rounded-pill)',
			},
		},
	},
	plugins: [],
	corePlugins: {
		preflight: false,
	},
} satisfies Config;
