/**
 * The normalized result of submitting a payment transaction.
 *
 * `referenceId` is generated by the consuming application. The remaining identifiers are
 * assigned by the payment implementation when available.
 */
export interface PaymentTransactionReference {
	vendor: string;
	isSuccess: boolean;
	lastRequestedAt: Date;
	referenceId: string;
	amount: PaymentAmount;
	transactionId?: string;
	reconciliationId?: string;
	completedAt?: Date;
	errorOccurredAt?: Date;
	errorCode?: string;
	errorMessage?: string;
}

/** Identifiers used to retrieve a payment transaction from an implementation. */
export interface PaymentTransactionLookup {
	vendor: string;
	referenceId?: string;
	transactionId?: string;
	reconciliationId?: string;
}

/**
 * Vendor-neutral reference to a stored payment instrument.
 *
 * The identifier is assigned by the payment implementation and is the only payment
 * instrument value required when submitting a subsequent charge.
 */
export interface PaymentInstrumentReference {
	vendor: string;
	paymentInstrumentId: string;
}

/**
 * Opaque payment-instrument registration data.
 *
 * `paymentToken` identifies the provider token, while the payment implementation defines
 * the payload shape. Neither value must be returned to callers.
 */
export interface PaymentInstrumentRegistration {
	paymentToken: string;
	payload: unknown;
}

/** Request to register a payment instrument for future charges. */
export interface CreatePaymentInstrumentRequest {
	paymentInstrumentRegistration: PaymentInstrumentRegistration;
}

/**
 * A currency amount expressed in the currency's smallest unit.
 *
 * For example, `{ amount: 1250, currency: 'USD' }` represents USD 12.50.
 */
export interface PaymentAmount {
	amount: number;
	currency: string;
}

/** A payment amount, stored instrument reference, and its submission result/reference. */
export interface PaymentTransactionSubmission {
	/** Caller-provided idempotency and reconciliation reference for this charge attempt. */
	referenceId: string;
	amount: PaymentAmount;
	paymentInstrument: PaymentInstrumentReference;
}

/** A refund amount and the completed transaction to refund. */
export interface PaymentTransactionRefundSubmission {
	amount: PaymentAmount;
	/** Caller-provided idempotency and reconciliation reference for this refund attempt. */
	referenceId: string;
	transaction: PaymentTransactionLookup;
}

/** The vendor-neutral recurrence for scheduled payment charges. */
export interface PaymentRecurrence {
	unit: 'day' | 'week' | 'month' | 'year';
	every: number;
}

/** The vendor-neutral schedule for a recurring payment. */
export interface PaymentSchedule {
	billingCycle: PaymentRecurrence;
	maximumCycles?: number;
}

/** Vendor-neutral reference to a recurring-payment plan managed by a payment implementation. */
export interface RecurringPaymentPlanReference {
	vendor: string;
	planId: string;
}

/** Identifiers used to retrieve a vendor-managed recurring-payment plan. */
export interface RecurringPaymentPlanLookup {
	vendor: string;
	planId: string;
}

/** The recurring terms of a payment plan. */
export interface RecurringPaymentPlan {
	vendorPlan?: RecurringPaymentPlanReference;
	amount: PaymentAmount;
	schedule: PaymentSchedule;
}

/** Terms used to create a reusable recurring-payment plan with a payment vendor. */
export interface CreateRecurringPaymentPlanRequest {
	amount: PaymentAmount;
	schedule: PaymentSchedule;
}

/** Recurring-payment plan terms supplied when creating or updating a payment. */
export type RecurringPaymentPlanSubmission =
	| {
			vendorPlan: RecurringPaymentPlanReference;
	  }
	| {
			amount: PaymentAmount;
			schedule: PaymentSchedule;
	  };

/** The lifecycle state of a recurring payment. */
export type RecurringPaymentStatus = 'pending' | 'active' | 'cancelled' | 'completed' | 'failed';

/** Identifiers used to retrieve a recurring payment from an implementation. */
export interface RecurringPaymentLookup {
	vendor: string;
	referenceId?: string;
	subscriptionId?: string;
}

/** Normalized state for a recurring payment. */
export interface RecurringPaymentReference {
	vendor: string;
	referenceId: string;
	subscriptionId?: string;
	status: RecurringPaymentStatus;
	paymentInstrument: PaymentInstrumentReference;
	plan: RecurringPaymentPlan;
	completedBillingCycles: number;
	startedAt?: Date;
	nextPaymentAt?: Date;
	cancelledAt?: Date;
	completedAt?: Date;
	errorCode?: string;
	errorMessage?: string;
}

/** A recurring payment configuration backed by a stored payment instrument. */
export interface RecurringPaymentSubmission {
	paymentInstrument: PaymentInstrumentReference;
	plan: RecurringPaymentPlanSubmission;
	referenceId: string;
}

/** An update to an existing recurring payment. */
export interface RecurringPaymentUpdate {
	recurringPayment: RecurringPaymentLookup;
	paymentInstrument?: PaymentInstrumentReference;
	plan?: RecurringPaymentPlanSubmission;
}

/** Minimal payment contract for managing instruments, transactions, and recurring payments. */
export interface PaymentService {
	createPaymentInstrument(request: CreatePaymentInstrumentRequest): Promise<PaymentInstrumentReference>;
	chargePayment(transaction: PaymentTransactionSubmission): Promise<PaymentTransactionReference>;
	refundPayment(refund: PaymentTransactionRefundSubmission): Promise<PaymentTransactionReference>;
	getPaymentTransaction(lookup: PaymentTransactionLookup): Promise<PaymentTransactionReference>;
	createRecurringPaymentPlan(request: CreateRecurringPaymentPlanRequest): Promise<RecurringPaymentPlanReference>;
	getRecurringPaymentPlan(lookup: RecurringPaymentPlanLookup): Promise<RecurringPaymentPlan>;
	createRecurringPayment(recurringPayment: RecurringPaymentSubmission): Promise<RecurringPaymentReference>;
	updateRecurringPayment(recurringPayment: RecurringPaymentUpdate): Promise<RecurringPaymentReference>;
	cancelRecurringPayment(recurringPayment: RecurringPaymentLookup): Promise<RecurringPaymentReference>;
}
