/**
 * The normalized result of submitting a payment transaction.
 *
 * `referenceId` is generated by the consuming application. The remaining identifiers are
 * assigned by the payment implementation when available.
 */
export interface PaymentTransactionReference {
	vendor: string;
	isSuccess: boolean;
	lastRequestedAt: Date;
	referenceId: string;
	amount: PaymentAmount;
	transactionId?: string;
	reconciliationId?: string;
	completedAt?: Date;
	errorOccurredAt?: Date;
	errorCode?: string;
	errorMessage?: string;
}

/** Identifiers used to retrieve a payment transaction from an implementation. */
export interface PaymentTransactionLookup {
	vendor: string;
	referenceId?: string;
	transactionId?: string;
	reconciliationId?: string;
}

/**
 * Vendor-neutral reference to a stored payment instrument.
 *
 * The identifier is assigned by the payment implementation and is the only payment
 * instrument value required when submitting a subsequent charge.
 */
export interface PaymentInstrumentReference {
	vendor: string;
	paymentInstrumentId: string;
}

/**
 * Opaque payment-instrument registration data.
 *
 * `paymentToken` identifies the provider token, while the payment implementation defines
 * the payload shape. Neither value must be returned to callers.
 */
export interface PaymentInstrumentRegistration {
	paymentToken: string;
	payload: unknown;
}

/** Request to register a payment instrument for future charges. */
export interface CreatePaymentInstrumentRequest {
	paymentInstrumentRegistration: PaymentInstrumentRegistration;
}

/**
 * A currency amount expressed in the currency's smallest unit.
 *
 * For example, `{ amount: 1250, currency: 'USD' }` represents USD 12.50.
 */
export interface PaymentAmount {
	amount: number;
	currency: string;
}

/** A payment amount, stored instrument reference, and its submission result/reference. */
export interface PaymentTransactionSubmission {
	/** Caller-provided idempotency and reconciliation reference for this charge attempt. */
	referenceId: string;
	amount: PaymentAmount;
	paymentInstrument: PaymentInstrumentReference;
}

/** A refund amount and the completed transaction to refund. */
export interface PaymentTransactionRefundSubmission {
	amount: PaymentAmount;
	/** Caller-provided idempotency and reconciliation reference for this refund attempt. */
	referenceId: string;
	transaction: PaymentTransactionLookup;
}

/** The vendor-neutral recurrence for scheduled payment charges. */
export interface PaymentRecurrence {
	unit: 'day' | 'week' | 'month' | 'year';
	every: number;
}

/** The vendor-neutral schedule for a recurring payment. */
export interface PaymentSchedule {
	billingCycle: PaymentRecurrence;
	maximumCycles?: number;
}

/** Vendor-neutral reference to a recurring-payment plan managed by a payment implementation. */
export interface RecurringPaymentPlanReference {
	vendor: string;
	planId: string;
}

/** Identifiers used to retrieve a vendor-managed recurring-payment plan. */
export interface RecurringPaymentPlanLookup {
	vendor: string;
	planId: string;
}

/** The recurring terms of a payment plan. */
export interface RecurringPaymentPlan {
	vendorPlan?: RecurringPaymentPlanReference;
	amount: PaymentAmount;
	schedule: PaymentSchedule;
}

/** Terms used to create a reusable recurring-payment plan with a payment vendor. */
export interface CreateRecurringPaymentPlanRequest {
	amount: PaymentAmount;
	schedule: PaymentSchedule;
}

/** Recurring-payment plan terms supplied when creating or updating a payment. */
export type RecurringPaymentPlanSubmission =
	| {
			vendorPlan: RecurringPaymentPlanReference;
	  }
	| {
			amount: PaymentAmount;
			schedule: PaymentSchedule;
	  };

/**
 * The normalized lifecycle state of a vendor-maintained subscription.
 */
export type SubscriptionStatus = 'created' | 'pending' | 'active' | 'suspended' | 'delinquent' | 'cancelled' | 'completed';

/** Identifiers used to retrieve a subscription from an implementation. */
export interface SubscriptionLookup {
	vendor: string;
	referenceId?: string;
	subscriptionId?: string;
}

/**
 * Normalized state for a vendor-maintained subscription.
 *
 * A reference is returned only after a vendor has created the subscription, so
 * `subscriptionId` always identifies the vendor resource.
 */
export interface SubscriptionReference {
	vendor: string;
	referenceId: string;
	subscriptionId: string;
	status: SubscriptionStatus;
	paymentInstrument: PaymentInstrumentReference;
	plan: RecurringPaymentPlan;
	completedBillingCycles: number;
	startedAt?: Date;
	nextPaymentAt?: Date;
	cancelledAt?: Date;
	completedAt?: Date;
	errorCode?: string;
	errorMessage?: string;
}

/**
 * A subscription configuration backed by a stored payment instrument.
 *
 * `startAt` is the requested start date passed to the payment provider. Providers may use
 * it to defer the first charge or to establish the subscription's billing schedule.
 */
export interface SubscriptionSubmission {
	paymentInstrument: PaymentInstrumentReference;
	plan: RecurringPaymentPlanSubmission;
	referenceId: string;
	startAt: Date;
}

/**
 * An amount-only update to an existing subscription.
 *
 * The payment instrument and assigned plan are intentionally immutable through this
 * contract because providers can attach side effects to changing either value.
 */
export interface SubscriptionUpdate {
	subscription: SubscriptionLookup;
	amount: PaymentAmount;
}

/** Minimal payment contract for managing instruments, transactions, and subscriptions. */
export interface PaymentService {
	createPaymentInstrument(request: CreatePaymentInstrumentRequest): Promise<PaymentInstrumentReference>;
	chargePayment(transaction: PaymentTransactionSubmission): Promise<PaymentTransactionReference>;
	refundPayment(refund: PaymentTransactionRefundSubmission): Promise<PaymentTransactionReference>;
	getPaymentTransaction(lookup: PaymentTransactionLookup): Promise<PaymentTransactionReference>;
	createRecurringPaymentPlan(request: CreateRecurringPaymentPlanRequest): Promise<RecurringPaymentPlanReference>;
	getRecurringPaymentPlan(lookup: RecurringPaymentPlanLookup): Promise<RecurringPaymentPlan>;
	createSubscription(subscription: SubscriptionSubmission): Promise<SubscriptionReference>;
	/** Retrieves the current vendor-maintained state of a subscription. */
	getSubscription(subscription: SubscriptionLookup): Promise<SubscriptionReference>;
	updateSubscription(subscription: SubscriptionUpdate): Promise<SubscriptionReference>;
	cancelSubscription(subscription: SubscriptionLookup): Promise<SubscriptionReference>;
}
