import type { Property } from '@ocom/data-sources-mongoose-models/property';
import { COMMUNITY_IDS } from './communities.ts';
import { MEMBER_IDS } from './members.ts';

const PROPERTY_IDS = {
	mainStreet: 'e00000000000000000000001',
	oakAvenue: 'e00000000000000000000002',
} as const;

export const properties = [
	{
		_id: PROPERTY_IDS.mainStreet,
		community: COMMUNITY_IDS.riverside,
		owner: MEMBER_IDS.testUserMember,
		propertyName: '123 Main Street',
		propertyType: 'Single Family',
		listedForSale: false,
		listedForRent: true,
		listedForLease: false,
		listedInDirectory: true,
		location: {
			position: {
				type: 'Point',
				coordinates: [-73.935242, 40.73061],
			},
			address: {
				streetNumber: '123',
				streetName: 'Main Street',
				municipality: 'Riverside',
				municipalitySubdivision: '',
				localName: 'Riverside',
				countrySecondarySubdivision: 'Riverside County',
				countryTertiarySubdivision: '',
				countrySubdivision: 'NY',
				countrySubdivisionName: 'New York',
				postalCode: '10001',
				extendedPostalCode: '',
				countryCode: 'US',
				country: 'United States',
				countryCodeISO3: 'USA',
				freeformAddress: '123 Main Street, Riverside, NY 10001',
				streetNameAndNumber: '123 Main Street',
				routeNumbers: '',
				crossStreet: '',
			},
		},
		listingDetail: {
			price: 350000,
			rentHigh: 2500,
			rentLow: 2000,
			lease: 12,
			maxGuests: 4,
			bedrooms: 3,
			bedroomDetails: [],
			bathrooms: 2,
			squareFeet: 1800,
			yearBuilt: 2005,
			lotSize: 5000,
			description: 'Spacious single family home in the heart of Riverside Community.',
			amenities: ['parking', 'laundry', 'central-air'],
			additionalAmenities: [],
			images: [],
			video: null,
			floorPlan: null,
			floorPlanImages: [],
			listingAgent: null,
			listingAgentPhone: null,
			listingAgentEmail: null,
			listingAgentWebsite: null,
			listingAgentCompany: null,
			listingAgentCompanyPhone: null,
			listingAgentCompanyEmail: null,
			listingAgentCompanyWebsite: null,
			listingAgentCompanyAddress: null,
		},
		tags: ['family-friendly', 'riverside'],
		hash: null,
		lastIndexed: null,
		updateIndexFailedDate: null,
		schemaVersion: '1.0.0',
		version: 0,
		createdAt: new Date('2024-03-01T00:00:00Z'),
		updatedAt: new Date('2024-03-01T00:00:00Z'),
	},
	{
		_id: PROPERTY_IDS.oakAvenue,
		community: COMMUNITY_IDS.riverside,
		owner: MEMBER_IDS.janeSmithMember,
		propertyName: '456 Oak Avenue',
		propertyType: 'Townhouse',
		listedForSale: true,
		listedForRent: false,
		listedForLease: false,
		listedInDirectory: true,
		location: {
			position: {
				type: 'Point',
				coordinates: [-73.942, 40.735],
			},
			address: {
				streetNumber: '456',
				streetName: 'Oak Avenue',
				municipality: 'Riverside',
				municipalitySubdivision: '',
				localName: 'Riverside',
				countrySecondarySubdivision: 'Riverside County',
				countryTertiarySubdivision: '',
				countrySubdivision: 'NY',
				countrySubdivisionName: 'New York',
				postalCode: '10002',
				extendedPostalCode: '',
				countryCode: 'US',
				country: 'United States',
				countryCodeISO3: 'USA',
				freeformAddress: '456 Oak Avenue, Riverside, NY 10002',
				streetNameAndNumber: '456 Oak Avenue',
				routeNumbers: '',
				crossStreet: '',
			},
		},
		listingDetail: {
			price: 275000,
			rentHigh: null,
			rentLow: null,
			lease: null,
			maxGuests: 2,
			bedrooms: 2,
			bedroomDetails: [],
			bathrooms: 1,
			squareFeet: 1200,
			yearBuilt: 2010,
			lotSize: 3000,
			description: 'Modern townhouse with open floor plan and community garden access.',
			amenities: ['garden-access', 'modern-kitchen'],
			additionalAmenities: [],
			images: [],
			video: null,
			floorPlan: null,
			floorPlanImages: [],
			listingAgent: null,
			listingAgentPhone: null,
			listingAgentEmail: null,
			listingAgentWebsite: null,
			listingAgentCompany: null,
			listingAgentCompanyPhone: null,
			listingAgentCompanyEmail: null,
			listingAgentCompanyWebsite: null,
			listingAgentCompanyAddress: null,
		},
		tags: ['townhouse', 'modern'],
		hash: null,
		lastIndexed: null,
		updateIndexFailedDate: null,
		schemaVersion: '1.0.0',
		version: 0,
		createdAt: new Date('2024-03-15T00:00:00Z'),
		updatedAt: new Date('2024-03-15T00:00:00Z'),
	},
] as unknown as Property[];
